-- ==========================================================================
-- 073 · QUERY 1 of 2 -- SURVEY ONLY. Read-only: nothing is written.
--
-- PREPARED, NOT RUN BY ME. Safe at any time.
--
-- ---------------------------------------------------------------------------
-- 🔴 WHY: the two recorded fines carry fine_percent = 0.00, and 0 is the 100
-- seen in a mirror.
--
-- This project spent a whole round on useState('100') writing a fine policy
-- nobody decided, and the lesson was: make "not decided yet" representable
-- instead of manufacturing an answer. The column does accept null now — check5
-- emptied both storages itself.
--
-- ⚠️ SO WHERE DID THE ZERO COME FROM? If the owner chose it, it is a policy. If
-- a screen wrote it untouched, it is the same fault in a worse disguise: 100 was
-- CONSPICUOUS — a number that stops you. Zero is never noticed, it means "never
-- fine anyone, ever", and it can sit for years without being asked.
--
-- ✅ HALF OF THIS IS ALREADY MEASURED, FROM THE CODE: the dialog now starts at
-- '' (StorageFormDialog.js:72), storagePayload sends null for blank
-- (storageForm.js:140), and storageForm.test.js pins `fine_percent: null` for
-- an untouched pair. ⚠️ THE CURRENT SCREEN CANNOT WRITE A ZERO IT WAS NOT GIVEN.
--
-- So the open question is historical, and this query is the half the repository
-- cannot answer: what the two storages carry RIGHT NOW. A fine copies the
-- storage's policy at posting time, so reading the storages says whether 0 is
-- live policy or a value that has since been changed underneath those rows.
--
-- WHAT TO LOOK AT:
--   • null on both columns  -> the fines' 0 came from somewhere no longer
--     reachable, and nothing new can inherit it
--   • 0 on both             -> it is live, and the next question is whether
--     anybody typed it
--   • 100 on both           -> the fines' 0 predates check5 and something else
--     wrote it, which is its own finding
-- ==========================================================================

-- ⚠️ to_jsonb(s) — THE WHOLE ROW, AND A FIRST DRAFT DID NOT DO THIS.
--
-- It named s.owner_employee_id, which has never been read in this thread:
-- check5 returned id · name · kind · fine_percent · fine_basis, and
-- storage_responsibles is a table of its own. The responsible may be a column
-- on storages or may not exist there at all — nobody has looked.
--
-- ⚠️ That is line_charged again, one round later. And worse: 072's header
-- carries a block naming the measurement behind every column in it, written
-- last round precisely to stop this — and the practice did not survive into the
-- next file. An invention that prevents one fault and is not applied to the
-- first file after it.
--
-- The cure is in this thread too: check3 escaped full_name because it read
-- to_jsonb(e) whole instead of picking columns, and that same row is what
-- surfaced profile_id and opened the identity question. storages is TWO rows.
-- A picked list buys nothing here and risks everything.
select
  to_jsonb(s)                                 as storage_row,
  (s.fine_percent is null and s.fine_basis is null) as policy_not_decided,
  -- ⚠️ coalesce, AND ITS ABSENCE HERE WAS 066c_5 REPEATED WORD FOR WORD.
  --
  -- `null = 0` is UNKNOWN, not false. So a column named "policy is zero"
  -- answered NEITHER in the one case it exists to tell apart from zero — the
  -- undecided policy.
  --
  -- ⚠️ And the fix was invented in this repository, by us, with the argument
  -- spelled out: "null = 'text' is UNKNOWN not false, in a column named
  -- expect_true". It did not carry into a file written after it — the same way
  -- 072's provenance block did not carry into 073_1. The rule keeps being
  -- applied only where it has already broken.
  coalesce(s.fine_percent = 0, false)         as policy_is_zero
from public.storages s
order by s.kind, s.name;
