-- دوال قاعدة البيانات — ملف مولَّد، لا تعدّله بالإيد.
--
-- كل تغيير على أي دالة بيتعكس هون بإعادة توليد، مش بتحرير السطر المتغيّر:
-- الملف قيمته إنه نسخة طبق الأصل عن القاعدة، وأول تعديل يدوي بيلغي هاي
-- القيمة بصمت — بتصير تقرأ وثيقة وإنت مفكّرها القاعدة.
--
-- شغّل هذا بمحرّر SQL والصق المخرج مكان كل شي تحت هذا الرأس:
--
--   select string_agg(pg_get_functiondef(p.oid), E'\n\n' order by p.proname)
--   from pg_proc p
--   join pg_namespace n on n.oid = p.pronamespace
--   where n.nspname = 'public' and p.prokind = 'f';
--
-- ليش pg_get_functiondef وليش مش prosrc: prosrc بيرجّع الجسم بس، وما بيقول
-- ولا إشي عن SECURITY DEFINER ولا search_path ولا اللغة. و CREATE OR REPLACE
-- بتصفّر كل خاصية ما بتعطيها إياها صراحةً — يعني إعادة بناء دالة من جسمها
-- لحاله بتسقط تحصيناتها بصمت. صار فعلًا مع seed_cancellation_reasons_for_salon.

-- ⏳ لسا ما انولّد لأول مرة. شغّل الاستعلام فوق والصق مخرجه هون.
